### ISSUE TITLE
Summary: Exceeds Expecatations

### ISSUE THREAD

**Issue by zannain** [MrMacvos/bwa-u3-jammming-prj#6]
Hey Marc! Great work on this application! Way to add the audio player into the application. I recommend testing how responsive it is because right now the user would have to scroll to the right to play the track. This generally does not make for a good user experience. You may need to play with the CSS settings to increase the width of the container. 

![image](https://user-images.githubusercontent.com/24375741/40263634-54d43416-5ae3-11e8-82ba-1a556a0050cc.png)

One of the most challenging parts of development is keeping up with how fast languages, framework, and technologies change.  A few React-specific resources I recommend looking into to help you stay up to date is the [Syntax.fm podcast](https://syntax.fm/). I also suggest reading up on React style guide I mentioned as this will help you incorporate best practices when writing React code. React is a library that has a lot of development behind it so newsletters are also a great way to keep up with the changes. Check out this [newsletter that was designed for developers](https://cooperpress.com/). **Keep up the really great work!!**

**Comment by MrMacvos** [comment]
Yeah :-) I noticed .. I work on 2560px wide screen and didn't want to spent time to make it mobile friendly. I'm doing that for my work right now with two projects, and it's not funny. So I didn't have the need for a third project ... plus, CCS styling had nothing to do with learning React / Node.
